title: "LoL Balance Group"
description: "A private space to discuss champion balance"
baseurl: "/LOLbalance"   # your repo name
url: "https://syoo96.github.io/LOLbalancer"
theme: minima                   # or your chosen theme
